### PR TITLE
Frontend API service & refactor, backend error standardization

### LINKED ISSUE #17: [Bug] Invalid access token on api requests causes page to become unresponsive
## Overview
In some circumstances, such as navigating to http://localhost:3000 after restarting the docker container without logging out first, the app will become unresponsive.

### Expected Behavior 

When an access token is invalid, the user should be brought to the login page, maybe with an indication that they've been logged out.

### Current Behavior
If a user has an expired/invalid access token in browser, api calls correctly return a 403. However, this 403 error is not handled properly and the page becomes unresponsive.

### Steps to Reproduce
This bug can happen during normal use, but this is a reliable way to reproduce it:
1. Log in with a valid username and password on http://localhost:3000/login
2. Using browser developer tools, find your access token in local storage
3. Edit the value of the access field in any way
4. Navigate to http://localhost:3000

### PR DESCRIPTION
**Pull request by joshuagerstein**
## Overview

This PR refactors the frontend to centralize API interactions and improve authentication state management. It also includes backend adjustments for standardized error responses and test environment authentication.

**Frontend Changes:**
 * Centralized API calls into `services/api.js` with an Axios client and JWT interceptors (request for token attachment, response for basic 401 logout via global event).
 * `AuthProvider` (`context/auth.js`) now manages `authTokens` (React state & `localStorage`) and `isAuthenticated` status, handling login/logout via a global event.
 * Data contexts (`PetitionerProvider`, `PetitionsProvider`) clear state on logout via the same global event. *(Note: Sensitive data remains in `location.state` for `/generate` route, to be addressed in a follow-up PR).*
 * Added `useIsMounted` hook to prevent state updates on unmounted components (credit: https://github.com/webNeat/react-tidy).
 * Refactored components to use the new API service, `AuthProvider`, and `useIsMounted`.
 * Minor CSS updates (disabled button appearance, removed redundant Bootstrap import).

**Backend Changes:**
 * API error responses now consistently use appropriate HTTP status codes and a `{"detail": "message"}` JSON body.
 * Configured Django REST Framework for JWT-only API authentication in general use, with SessionAuthentication enabled specifically for the Pytest environment.

**Note for Reviewer:**
Token refresh is not included yet (access tokens are temporarily longer). There are no automated frontend tests, manual testing is required.
**Additionally, as I am relatively new to React, I am very open to feedback on best practices, architectural choices, and any areas that could benefit from refactoring if you spot opportunities for improvement.**

### Does this close any currently open issues?

Closes #17, #24, #38, #60

### Testing Instructions

**1. Login & Logout Flow:**
 - [ ] Log in with valid credentials.
   - *Verify:* Redirect to attorney selection. `authTokens` in `localStorage`. `AuthProvider` state (`isAuthenticated`, `authTokens`) is correct.
 - [ ] Attempt login with invalid credentials.
   - *Verify:* Error message from backend `detail` key is displayed.
 - [ ] Click on logout in the navbar.
   - *Verify:* Redirect to login. Logout message from `sessionStorage` displayed. `localStorage` tokens cleared. `AuthProvider` state reset.

**2. Authenticated API Calls & Basic Error Handling:**
 - [ ] After login, verify data dependent on authenticated API calls (e.g., attorney list) loads via the new API service.
 - [ ] Upload a PDF known to cause a server-side parsing error (e.g., not from PA courts).
   - *Verify:* Backend returns `500 Internal Server Error`. Frontend displays an error message from the `detail` key.

**3. `401 Unauthorized` Error Handling (Session Expiry Simulation):**
 - [ ] After login, manually corrupt/delete the `access` token in `localStorage`.
 - [ ] Trigger an authenticated API call (e.g., refresh `/`, submit uploaded files, generate petition).
   - *Verify:* Logout is triggered, tokens cleared (context & `localStorage`), redirect to login with session expiry message.

**4. Context Data Clearing on Logout:**
 - [ ] Populate `PetitionerProvider` and `PetitionsProvider` by uploading PDFs and proceeding to review page.
 - [ ] Log out.
   - *Verify (React DevTools or by logging back in):* State in these providers is reset.

**5. Handling missing petition data on routes that require it:**
 - [ ] Ensure petitioner/petition contexts are empty (e.g., perform a fresh login and do not upload any files).
 - [ ] Manually navigate directly to `/generate` or `/review`.
   - *Verify:* You are redirected to the main landing page (`/`) without any application errors or significant delay.

### CODE REVIEW

File: frontend/src/src/PrivateRoute.js [hunk 1]
```diff
@@ -1,13 +1,22 @@
 import React from 'react';
-import { Route, Redirect } from 'react-router-dom';
+import {Route, Redirect, useLocation} from 'react-router-dom';
```
Comment (dnlsngr) [inline frontend/src/src/PrivateRoute.js]: this is showing up in a lot of places, it looks like your autoformatter is set to "no spaces" on named imports--if it's not too hard, would be nice to change that so you're not battling against others when you make changes. I know I've had cases where prettier is haunted, so if its giving you trouble, it's easy enough to figure it out another time and submit a formatting PR that minimal review

File: frontend/src/src/PrivateRoute.js [hunk 2]
```diff
@@ -1,13 +1,22 @@
...
     return (
-        <Route {...rest} render={props =>
-            authTokens ? <Component {...props} /> : <Redirect to="/login" />}
+        <Route
+            {...rest}
+            render={props => {
+                if (isAuthenticated) {
+                    return <Component {...props} />;
+                } else {
+                    console.log('PrivateRoute: Not authenticated, redirecting to /login. From:', location.pathname);
```
Comment (dnlsngr) [inline frontend/src/src/PrivateRoute.js]: optional, but a common pattern is to throw the failed pathname in a `next` query parameter on the login page (e.g. docketparse.com/login?next=/petitions), which would obviate the need for this logging and also let you put the user back where they're trying to go after they login

File: frontend/src/src/components/FileUpload/components/UploadModal.js [hunk 3]
```diff
@@ -1,116 +1,170 @@
...
         }
-    }
 
-    // Add new files
-    function uploadDocs(docs) {
-        const newFiles = Array.from(docs, checkFileType).filter(file => file !== undefined);
-        const newFileNames = new Set(newFiles.map((file) => file.name));
-        const oldUniqueFiles = uploadedFiles.filter((file) => !newFileNames.has(file.name));
-        setUploadedFiles([...oldUniqueFiles, ...newFiles]);
+        let updatedCombinedFiles = [...uploadedFiles];
```
Comment (dnlsngr) [inline frontend/src/src/components/FileUpload/components/UploadModal.js]: this might be a bit more javascripty if you iterated over these files and created an object where the key is "name", then you would just be doing an object key assignment, and you could grab Object.values() at the end to make it an array. It won't matter here, but it's more performant for large datasets, and so I think most devs would try to use a map when they find themselves iterating through an array looking for uniqueness

File: frontend/src/src/components/LandingPage/index.js [hunk 4]
```diff
@@ -1,106 +1,149 @@
...
+    const getIsMounted = useIsMounted();
 
-    // useEffect is the React Hook equivalent to ComponentDidMount
+    // Fetches the list of attorneys to populate form options.
     useEffect(() => {
-        const token = `Bearer ${authTokens.access}`;
-        var config = {
-            'headers': { 'Authorization': token }
-        };
+        if (isAuthenticated) {
```
Comment (dnlsngr) [inline frontend/src/src/components/LandingPage/index.js:24]: This block really shows where getIsMounted is killing you--you have that check in 3 places in this function. A good activity for a future ticket is removing one of them, recreating the warning, and then seeing what's causing us to unmount things before we operate on them

File: frontend/src/src/components/ReviewPage/index.js [hunk 5]
```diff
@@ -81,7 +84,7 @@ export default function ReviewPage(props) {
         })
     }, [petitioner, petitions])
 
-    function postGeneratorRequest(petitioner, petition, index) {
+    async function postGeneratorRequest(petitioner, petition, index) {
```
Comment (dnlsngr) [inline frontend/src/src/components/ReviewPage/index.js:87]: style nit: we don't use the function keyword in most places, just arrow functions

**Review by dnlsngr — APPROVED** [review]
Left some notes, everything is style or suggested approach--giving it the thumbs up, pending clearing out the commented code, and take whatever of the suggestions you like

File: frontend/src/src/components/ReviewPage/index.js (hunk 5 above)
Comment (joshuagerstein) [reply frontend/src/src/components/ReviewPage/index.js:87]: Noted. I will do a pass to replace `function` with arrow functions along with some other formatting things in a future PR. Is there anywhere that it's appropriate to keep `function` keyword in the code?

File: frontend/src/src/PrivateRoute.js (hunk 2 above)
Comment (joshuagerstein) [reply frontend/src/src/PrivateRoute.js]: Done. However, I get immediately redirected from `/login?next=/something` to `/login` (maybe related to StrictMode?). I put a TODO in the login component to handle the `next` parameter.

File: frontend/src/src/components/FileUpload/components/UploadModal.js (hunk 3 above)
Comment (joshuagerstein) [reply frontend/src/src/components/FileUpload/components/UploadModal.js]: Addressed [here](https://github.com/Philadelphia-Lawyers-for-Social-Equity/PA_Expunger/pull/62/commits/4a5da8ca50b1d249ba0f49e709ed6664cc5955ba)

File: frontend/src/src/components/ReviewPage/index.js (hunk 5 above)
Comment (dnlsngr) [reply frontend/src/src/components/ReviewPage/index.js:87]: I always forget, they handle `this` binding differently--my rule is use arrow operators until they aren't doing what you expect, then try function
